version: '3.9'
services:
  nginx:
    build:
      context: ./nginx_service
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./nginx_service/index.html:/usr/share/nginx/html/index.html:ro
    restart: always
