version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: hidden_service_nginx
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  tor:
    build:
      context: ./tor
      dockerfile: Dockerfile
    container_name: hidden_service_tor
    user: root
    restart: unless-stopped

  ssh:
    image: linuxserver/openssh-server
    container_name: ssh_server
    ports:
      - "2222:22"
    environment:
      - USER_NAME=${USER_NAME}
      - USER_PASSWORD=${USER_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD_ACCESS=true
    restart: unless-stopped