version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: hidden_service_nginx
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  tor:
    build:
      context: ./tor
      dockerfile: Dockerfile
    container_name: hidden_service_tor
    user: root
    restart: unless-stopped

