networks:
  hidden_network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: hidden_service_nginx
    networks:
      - hidden_network
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  tor:
    build:
      context: ./tor
      dockerfile: Dockerfile
    container_name: hidden_service_tor
    networks:
      - hidden_network
    user: root
    restart: unless-stopped

  ssh:
    build:
      context: ./ssh
      dockerfile: Dockerfile
    container_name: ssh_server
    networks:
      - hidden_network
    volumes:
      - ./ssh/sshd_config:/etc/ssh/sshd_config:ro
    ports:
      - "42424:22"
    restart: unless-stopped


